---
output: 
  html_document:
    toc: false
    toc_depth: 1
    toc_float: 
      collapsed: false
---
<div id="backtop"><a href="#">TOP</a></div>
<div id="backhome"><a href="index.html">HOME</a></div>
<br>
<br>
<br>

#<font face="Brush Script MT" size=7>**About Us**</font> {.tabset}
##<font face="High Tower Text" size=4>Company History and Philosophy</font>
<center>
<font face="Algerian" color=black size=8>FISHMARKET INC.</font>

<font face="Belwe" color=black size=5>*¡°Seafood, Meats and Specialty Foods¡±*</font>
</center>

<br>

<font face="Times New Roman" size=3><b>
Established in 1988 by Jere and Steven Smith, Fishmarket Inc. was solely a seafood processor/distributor carrying the finest in fresh, frozen, live and value-added seafood products. The mission statement for the company was, ¡°provide our best product with our best service at our best price¡±. Although it may not be ¡°trendy¡±, this statement is true to our core beliefs as a company and remains our mission statement today! The company sold their products to retailers, restaurants, hotels and restaurants throughout the Midwest.

In 1998, Steven¡¯s twin brother, Bradley Smith joined the company. With the team together, the company began to expand into other areas as requested by our customers. In 2005, we purchased Kiefer Meats, bringing on a full line of beef, pork, lamb and veal to the mix of products we offered. In 2005 we also purchased Copper Kettle Co. moving the company into the production of specialty cheese spreads and dips.

As our company has grown from strictly a seafood company to a full line distributor/processor, we have never lost sight of our ¡°local¡± family of producers. Hence, we have been a member of ¡°Kentucky Proud¡± since its inception. We carry over 300 shelf stable items from local family farms and producers. We also procure Kentucky grown beef and pork along with specialty cheeses made here in Kentucky! In addition, we are producing a variety of breaded products such as; breaded pickles, green tomatoes, chicken tenders, oysters and cod just to name a few, under the ¡°Smith¡¯s Family Market¡± brand.

As you can see, <font color=red size=4.5>¡°We Aren¡¯t Just Seafood Anymore¡±</font>! We have grown as our customers have requested of us and positioned our company to be a supplier of the best Seafood, Meats and Specialty Foods to Retailers and the Foodservice industry in the Midwest. We are proud of our growth and will continue to seek innovative and aggressive ways to manufacture and distribute our vast array of products to all. All this while staying firm in mission statement of ¡°provide our best product with our best service at our best price¡±.

Sincerely,  
*Steven C Smith*  
*Bradley W Smith*
</b></font>

##<font face="High Tower Text" size=4>Events</font>
###2017
- balabala

###2016
- balabala

##<font face="High Tower Text" size=4>Photos</font>

##<font face="High Tower Text" size=4>Our Location</font>

<center><font face="High Tower Text" color=black size=6>*1406 West Chestnut St, Louisville, KY 40203*</font></center>

<br>

<style>
img {
  width: 2000px;
  display: block;
  margin: 0 auto;
}
</style>

```{r,location,echo=FALSE,warning=FALSE,message=FALSE,eval=T}
library(ggmap)
mapImageData=get_map(location=c(lon=-85.7750,lat=38.2505),
                     color="color",
                     source="google",
                     maptype="roadmap",
                     zoom=17)
ggmap(mapImageData,
      extent="device",
      ylab="Latitude",
      xlab="Longitude")
```

